# Generated by Django 3.2.4 on 2021-07-27 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('song_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=2000)),
                ('singer', models.CharField(max_length=2000)),
                ('tag', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='media/documents')),
                ('song', models.FileField(upload_to='media/documents')),
            ],
        ),
    ]
