# Generated by Django 3.2.4 on 2021-07-27 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicbeats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='tag',
            new_name='tags',
        ),
    ]
