# Generated by Django 3.2.4 on 2021-07-30 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musicbeats', '0002_rename_tag_song_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListenLater',
            fields=[
                ('listen_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('audio_id', models.CharField(default='', max_length=100000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
